#!/bin/bash -eu
set -o pipefail

log() { echo >&2 "[release] $*"; }

# TODO check on master branch
# TODO check up-to-date with remote repo

log "Bumping version number..."
npm version minor

log "Committing changes..."
git add package.json
newVersion="$(jq .version package.json)"
git commit -m"Bumped version to $newVersion"

log "Tagging release..."
git tag "v$newVersion"

log "Pushing to git..."
git push --tags
git push

log "Publishing to npm..."
npm publish

log "Completed OK."
